export interface District {
  name: string;
}

export interface Province {
  name: string;
  districts: District[];
}

export const vietnamLocations: Province[] = [
  {
    name: "An Giang",
    districts: [
      { name: "Thành phố Long Xuyên" },
      { name: "Thành phố Châu Đốc" },
      { name: "Huyện An Phú" },
      { name: "Thị xã Tân Châu" },
      { name: "Huyện Châu Phú" },
      { name: "Huyện Châu Thành" },
      { name: "Huyện Chợ Mới" },
      { name: "Huyện Phú Tân" },
      { name: "Huyện Thoại Sơn" },
      { name: "Huyện Tịnh Biên" },
      { name: "Huyện Tri Tôn" },
    ],
  },
  {
    name: "Bà Rịa - Vũng Tàu",
    districts: [
      { name: "Thành phố Vũng Tàu" },
      { name: "Thành phố Bà Rịa" },
      { name: "Huyện Châu Đức" },
      { name: "Huyện Đất Đỏ" },
      { name: "Huyện Long Điền" },
      { name: "Huyện Xuyên Mộc" },
      { name: "Huyện Côn Đảo" },
    ],
  },
  {
    name: "Bạc Liêu",
    districts: [
      { name: "Thành phố Bạc Liêu" },
      { name: "Huyện Đông Hải" },
      { name: "Huyện Hòa Bình" },
      { name: "Huyện Hồng Dân" },
      { name: "Huyện Phước Long" },
      { name: "Thị xã Giá Rai" },
    ],
  },
  {
    name: "Bắc Giang",
    districts: [
      { name: "Thành phố Bắc Giang" },
      { name: "Huyện Hiệp Hòa" },
      { name: "Huyện Lạng Giang" },
      { name: "Huyện Lục Nam" },
      { name: "Huyện Lục Ngạn" },
      { name: "Huyện Sơn Động" },
      { name: "Huyện Tân Yên" },
      { name: "Huyện Việt Yên" },
      { name: "Huyện Yên Dũng" },
      { name: "Huyện Yên Thế" },
    ],
  },
  {
    name: "Hà Nội",
    districts: [
      { name: "Quận Ba Đình" },
      { name: "Quận Hoàn Kiếm" },
      { name: "Quận Đống Đa" },
      { name: "Quận Hai Bà Trưng" },
      { name: "Quận Hoàng Mai" },
      { name: "Quận Thanh Xuân" },
      { name: "Quận Cầu Giấy" },
      { name: "Quận Tây Hồ" },
      { name: "Quận Long Biên" },
      { name: "Quận Bắc Từ Liêm" },
      { name: "Quận Nam Từ Liêm" },
      { name: "Thị xã Sơn Tây" },
      { name: "Huyện Ba Vì" },
      { name: "Huyện Chương Mỹ" },
      { name: "Huyện Đan Phượng" },
      { name: "Huyện Đông Anh" },
      { name: "Huyện Gia Lâm" },
      { name: "Huyện Hoài Đức" },
      { name: "Huyện Mê Linh" },
      { name: "Huyện Mỹ Đức" },
      { name: "Huyện Phú Xuyên" },
      { name: "Huyện Phúc Thọ" },
      { name: "Huyện Quốc Oai" },
      { name: "Huyện Sóc Sơn" },
      { name: "Huyện Thạch Thất" },
      { name: "Huyện Thanh Oai" },
      { name: "Huyện Thanh Trì" },
      { name: "Huyện Thường Tín" },
      { name: "Huyện Ứng Hòa" },
    ],
  },
  {
    name: "TP Hồ Chí Minh",
    districts: [
      { name: "Quận 1" },
      { name: "Quận 3" },
      { name: "Quận 5" },
      { name: "Quận 7" },
      { name: "Quận 10" },
      { name: "Quận 11" },
      { name: "Quận Bình Thạnh" },
      { name: "Quận Gò Vấp" },
      { name: "Quận Phú Nhuận" },
      { name: "Thành phố Thủ Đức" },
      { name: "Huyện Bình Chánh" },
      { name: "Huyện Củ Chi" },
      { name: "Huyện Hóc Môn" },
      { name: "Huyện Nhà Bè" },
      { name: "Huyện Cần Giờ" },
    ],
  },
  {
    name: "Đà Nẵng",
    districts: [
      { name: "Quận Hải Châu" },
      { name: "Quận Thanh Khê" },
      { name: "Quận Sơn Trà" },
      { name: "Quận Ngũ Hành Sơn" },
      { name: "Quận Liên Chiểu" },
      { name: "Huyện Hòa Vang" },
      { name: "Huyện Hoàng Sa" },
    ],
  },
  {
    name: "Bình Dương",
    districts: [
      { name: "Thành phố Thủ Dầu Một" },
      { name: "Thành phố Dĩ An" },
      { name: "Thành phố Thuận An" },
      { name: "Thị xã Tân Uyên" },
      { name: "Thị xã Bến Cát" },
      { name: "Huyện Bắc Tân Uyên" },
      { name: "Huyện Phú Giáo" },
      { name: "Huyện Dầu Tiếng" },
    ],
  },
  {
    name: "Đồng Nai",
    districts: [
      { name: "Thành phố Biên Hòa" },
      { name: "Thành phố Long Khánh" },
      { name: "Huyện Long Thành" },
      { name: "Huyện Nhơn Trạch" },
      { name: "Huyện Vĩnh Cửu" },
      { name: "Huyện Trảng Bom" },
      { name: "Huyện Thống Nhất" },
      { name: "Huyện Xuân Lộc" },
      { name: "Huyện Cẩm Mỹ" },
      { name: "Huyện Định Quán" },
      { name: "Huyện Tân Phú" },
    ],
  },
  {
    name: "Cần Thơ",
    districts: [
      { name: "Quận Ninh Kiều" },
      { name: "Quận Bình Thủy" },
      { name: "Quận Cái Răng" },
      { name: "Quận Ô Môn" },
      { name: "Quận Thốt Nốt" },
      { name: "Huyện Cờ Đỏ" },
      { name: "Huyện Phong Điền" },
      { name: "Huyện Vĩnh Thạnh" },
    ],
  },
  {
    name: "Bình Thuận",
    districts: [
      { name: "Thành phố Phan Thiết" },
      { name: "Thị xã La Gi" },
      { name: "Huyện Bắc Bình" },
      { name: "Huyện Hàm Thuận Bắc" },
      { name: "Huyện Hàm Thuận Nam" },
      { name: "Huyện Hàm Tân" },
      { name: "Huyện Tuy Phong" },
      { name: "Huyện Tánh Linh" },
      { name: "Huyện Đức Linh" },
      { name: "Huyện Phú Quý" },
    ],
  },
  {
    name: "Gia Lai",
    districts: [
      { name: "Thành phố Pleiku" },
      { name: "Thị xã An Khê" },
      { name: "Thị xã Ayun Pa" },
      { name: "Huyện Chư Păh" },
      { name: "Huyện Chư Prông" },
      { name: "Huyện Chư Pưh" },
      { name: "Huyện Chư Sê" },
      { name: "Huyện Đắk Đoa" },
      { name: "Huyện Đắk Pơ" },
      { name: "Huyện Đức Cơ" },
      { name: "Huyện Ia Grai" },
      { name: "Huyện Ia Pa" },
      { name: "Huyện KBang" },
      { name: "Huyện Kông Chro" },
      { name: "Huyện Krông Pa" },
      { name: "Huyện Mang Yang" },
      { name: "Huyện Phú Thiện" },
    ],
  },
  {
    name: "Ninh Thuận",
    districts: [
      { name: "Thành phố Phan Rang - Tháp Chàm" },
      { name: "Huyện Bác Ái" },
      { name: "Huyện Ninh Hải" },
      { name: "Huyện Ninh Phước" },
      { name: "Huyện Ninh Sơn" },
      { name: "Huyện Thuận Bắc" },
      { name: "Huyện Thuận Nam" },
    ],
  },
  {
    name: "Kiên Giang",
    districts: [
      { name: "Thành phố Rạch Giá" },
      { name: "Thành phố Hà Tiên" },
      { name: "Thành phố Phú Quốc" },
      { name: "Huyện An Biên" },
      { name: "Huyện An Minh" },
      { name: "Huyện Châu Thành" },
      { name: "Huyện Giang Thành" },
      { name: "Huyện Giồng Riềng" },
      { name: "Huyện Gò Quao" },
      { name: "Huyện Hòn Đất" },
      { name: "Huyện Kiên Hải" },
      { name: "Huyện Kiên Lương" },
      { name: "Huyện Tân Hiệp" },
      { name: "Huyện U Minh Thượng" },
      { name: "Huyện Vĩnh Thuận" },
    ],
  },
];
